apiVersion: v1
kind: Secret
metadata:
  name: user-crud-secret
type: Opaque
data:
  APP_KEY: {{ .Values.service.appKey  | b64enc | quote }}
  DB_PORT: {{ .Values.postgresql.service.port  | b64enc | quote }}
  DB_CONNECTION: {{ .Values.service.dbConnection  | b64enc | quote }}
  DB_HOST: {{ include "postgresql.fullname" .  | b64enc | quote }}
  DB_DATABASE: {{ .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.postgresqlUsername  | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword  | b64enc | quote }}