apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "crud-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/tipsypenguin($|/)(.*)
            backend:
              serviceName: {{ include "crud-chart.fullname" . }}
              servicePort: {{ .Values.service.port }}